Repository splor-mg/handbook, pull requests merged in 2025-05, with the labels that each got.

#83 Altera a versão do Python do projeto para 3.12.
  poetry.lock
  pyproject.toml
Labels: enhancement

#84 81 post treinamento dcppn
  docs/blog/.authors.yml
  docs/blog/posts/20250508_01_treinamento_dcppn.md
Labels: documentation

#86 Dever post treinamento
  docs/blog/posts/20250508_(Daniel)_treinamento_dcppn.md
  docs/blog/posts/20250508_01_treinamento_dcppn copy.md
Labels: documentation

#87 Revert "Dever post treinamento"
  docs/blog/posts/20250508_(Daniel)_treinamento_dcppn.md
  docs/blog/posts/20250508_01_treinamento_dcppn.md
Labels: bug

#91 Inclui post sobre transcrição de gravações.
  docs/blog/posts/20250514_transcricao_videos.md
Labels: documentation, enhancement

#92 Post do vídeo de reunião
  docs/blog/.authors.yml
  docs/blog/posts/20250514_gravacao_de_reuniao _dcppn.md
Labels: documentation
